# menu
menu:
  Home: .
  Archives: archives 
  Categories: categories  
 # Tags: tags  
 # Repository: repository  
  Books: books  
 # Links: links  
  About: about  

# Enable/Disable menu icons
menu_icons:
  enable: true  # æ˜¯å¦å¯ç”¨å¯¼èˆªèœå•å›¾æ ‡
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
 # tags: icon-tags
  repository: icon-project
  books: icon-book-fill
 # links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: true
    width: 40
    height: 40
    url: ../images/111.JPG
  title: stephen # é¡µé¢title
  favicon: ../images/111.JPG
 # board: <p>æ¬¢è¿äº¤æµä¸åˆ†äº«ç»éªŒ!</p> # ç«™ç‚¹å…¬å‘Š
  copyright: false # åº•éƒ¨ç‰ˆæƒä¿¡æ¯

# config
config:
  skin: theme-white # ä¸»é¢˜é¢œè‰² theme-black theme-blue theme-green theme-purple
  layout: main-center # å¸ƒå±€æ–¹å¼ main-left main-center main-right
  toc: true # æ˜¯å¦å¼€å¯æ–‡ç« ç« èŠ‚ç›®å½•å¯¼èˆª
  menu_highlight: false # æ˜¯å¦å¼€å¯å½“å‰èœå•é«˜äº®æ˜¾ç¤º
  thumbnail: true # enable posts thumbnail, options: true, false
  excerpt_link: Read More
  isNewTabLinks: false #æ˜¯å¦é“¾æ¥æ‰“å¼€æ–°æ ‡ç­¾é¡µ
  autoUnfold: true # é»˜è®¤å±•å¼€æ–‡ç« ç›®å½•

# Pagination
pagination:
  number: false
  prev: 
    alwayShow: true
  next:
    alwayShow: true
  midSize: 2 # å½“å‰é¡µç å·¦å³åˆ°çœç•¥å·æ˜¾ç¤ºçš„é¡µç æ•°ï¼Œé»˜è®¤2ï¼Œè¡¨ç°ä¸º 1 ... 4 5 6 7 8 ... 10
  showContent: true # é¡µé¢æ–‡ç« å°äº2ç¯‡æ—¶æ˜¾ç¤ºæ–‡ç« å†…å®¹

# Sidebar
sidebar: right
widgets: 
  - recent_posts
  - tagcloud
  - category
  - archive
# - tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# widget behavior
archive_type: 'monthly'
show_count: true

# Fancybox
fancybox: false

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

donate:
  enable: false
  wechatpay:
    qrcode: images/donate/wechatpayimg.png
    title: å¾®ä¿¡æ”¯ä»˜
  alipay: 
    qrcode: images/donate/alipayimg.png 
    title: æ”¯ä»˜å®

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: false # æ˜¯å¦å¯ç”¨åˆ†äº«
  sites: weibo,qq,wechat,facebook,twitter  # PCç«¯æ˜¾ç¤ºçš„åˆ†äº«å›¾æ ‡
  mobile_sites: weibo,qq,qzone  # ç§»åŠ¨ç«¯æ˜¾ç¤ºçš„åˆ†äº«å›¾æ ‡

repository:
  platform: github # æ‰˜ç®¡å¹³å°ï¼ˆgithub | giteeï¼‰
  username: cofess # ç”¨æˆ·å

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type: valine  # å¯ç”¨å“ªç§è¯„è®ºç³»ç»Ÿ
  disqus:  # enter disqus shortname here
  youyan: 
    uid: 1783844 # enter youyan uid 
  livere:
    uid: # enter youyan uid 
  gitment:
    githubID: 
    repo: 
    ClientID: 
    ClientSecret: 
    lazy: false
  gitalk: # gitalk. https://gitalk.github.io/
    owner:  #å¿…é¡». GitHub repository æ‰€æœ‰è€…ï¼Œå¯ä»¥æ˜¯ä¸ªäººæˆ–è€…ç»„ç»‡ã€‚
    admin:  #å¿…é¡». GitHub repository çš„æ‰€æœ‰è€…å’Œåˆä½œè€… (å¯¹è¿™ä¸ª repository æœ‰å†™æƒé™çš„ç”¨æˆ·)ã€‚
    repo:  #å¿…é¡». GitHub repository.
    ClientID:  #å¿…é¡». GitHub Application Client ID.
    ClientSecret:  #å¿…é¡». GitHub Application Client Secret.
    enableHotKey: true
    language: zh-CN
    
  valine: # Valine. https://valine.js.org
    appid:  # your leancloud application appid
    appkey:  # your leancloud application appkey
    notify: false # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: Just go go # comment box placeholder
    avatar: mm # gravatar style
    meta: nick,mail,link # custom comment header
    pageSize: 10 # pagination size
    visitor: false # Article reading statistic https://valine.js.org/visitor.html

# douban è±†ç“£ä¹¦å•
# Apiï¼š
  # https://developers.douban.com/wiki/?title=book_v2 å›¾ä¹¦
  # https://developers.douban.com/wiki/?title=movie_v2 ç”µå½±
# booksï¼š  
  # https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 ä¸ªäººä¹¦å•åˆ—è¡¨

douban:
 id: 181263519 # è±†ç“£ç”¨æˆ·å
 start: 0 # ä»å“ªä¸€æ¡è®°å½•å¼€å§‹
 count: 100 # è·å–è±†ç“£ä¹¦å•æ•°æ®æ¡æ•°
 apikey: https://api.douban.com/v2/book/user/:name/collections?start=0&count=100
  
# PV
pv:
  busuanzi:
    enable: false  # ä¸è’œå­ç»Ÿè®¡
  leancloud:
    enable: false  # leancloudç»Ÿè®¡
    app_id: # leancloud <AppID>
    app_key: # leancloud <AppKey>
        
# wordcount
postCount:
  enable: true
  wordcount: true  # æ–‡ç« å­—æ•°ç»Ÿè®¡
  min2read: false  # é˜…è¯»æ—¶é•¿é¢„è®¡ 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: true 
  avatar: ../images/111.JPG
  gravatar: 
  author: ä¸€é¢—èµ›è‰‡
  author_title: UE Designer
  author_description: è¢«è¯¯è§£æ˜¯è¡¨è¾¾è€…çš„å®¿å‘½
  location: chongqing, China
# follow: https://github.com/cofess

  social:
    links:
      ç«™é…·: https://www.zcool.com.cn/studio
      è±†ç“£: https://www.douban.com/people/181263519/?_i=1291074YoTuMM0
      pinterest: https://www.pinterest.com/ssssstephen/
    link_tooltip: true # enable the social link tooltip, options: true, false

  skills:
    ä¸“ä¸šèƒ½åŠ›: ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ—
    æ²Ÿé€šèƒ½åŠ›: ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ‘
    æ‰§è¡ŒåŠ›: ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ•
    å­¦ä¹ èƒ½åŠ›: ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ‘
    å›¢é˜Ÿåä½œ: ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ• ğŸŒ‘
    
  links:
    ç«™é…·: https://zcool.com.cn/studio
    è±†ç“£: https://douban.com/people/181263519
   # pinterest: https://pinterest.com/ssssstephen

  labels:
    - äº¤äº’è®¾è®¡
    - äº§å“è®¾è®¡
    - é“²å±å®˜
    - é˜…è¯»çˆ±å¥½è€…
    - æ•°å­—åª’ä½“
    - bugåˆ¶é€ è€…
  # My Personal Works
  works:
    å¸‚åœºITæ”¯æ’‘ç³»ç»Ÿ:
      link: 
      date: 2023
    ç‰§åœºæ‰‹æ™ºæ…§ç•œç‰§ç®¡ç†å¹³å°:
      link: 
      date: 2023
    ä¸­ç§»ç‰©è”ç½‘å®˜ç½‘:
      link: 
      date: 2022
    OneNETç»Ÿä¸€èåˆå¹³å°:
      link: 
      date: 2022
  # My Personal Projects
  projects:
    ç‰§å¸®æ‰‹æ™ºæ…§ç•œç‰§ç®¡ç†å¹³å°: 
    ä¸­å±±æ¡ˆä»¶å®¡æ‰¹ç³»ç»Ÿ: 

    